### ISSUE TITLE
Q: Process iOS GPS data

### ISSUE THREAD

**Issue by whisper-bye** [wearereasonablepeople/KalmanFilter#8]
I am new here about Kalman Filter algorithm,
I want use this library to filter my CLLocationCoordinate2D array,
but I don't know how to do this,
can you please give me some advice?
thx a lot!

**Comment by alickbass** [comment]
Hi @whisper-bye! Thanks for reaching us out!

First of all, I would really recommend reading [this page](https://en.wikipedia.org/wiki/Kalman_filter#Details) and understanding what you need to prepare.

**Comment by whisper-bye** [comment]
@alickbass 
thx for your quick reply, but I am not good at math..
It is too difficult for me

**Comment by alickbass** [comment]
This library was designed to provide an implementation of Kalman Filter regardless of the use cases. So it is up to you to decide how to use it. 

In your case, I would use `state estimate` matrix for locations and `error covariance` for the accuracy of that locations. However, the trickiest part is to understand what `covariance of the process noise` and `covariance of the observation noise` are.

Unfortunately, that is all I can give to you. You can also try to get some data from [here](https://github.com/lacker/ikalman) and use it with this library. But I heard also different opinions on the results of that library

**Comment by whisper-bye** [comment]
@alickbass 
thanks for your good advice, I will start to handle this
